# Generated by Django 3.1.4 on 2020-12-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='starting_bid',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('TO', 'Toys'), ('FA', 'Fashion'), ('EL', 'Electronics'), ('HO', 'Home'), ('OT', 'Others')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='imageURL',
            field=models.URLField(null=True),
        ),
    ]
