# Generated by Django 3.1.4 on 2020-12-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='user_id',
            new_name='user',
        ),
    ]
