# Generated by Django 3.1.4 on 2021-01-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201229_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('TO', 'Toys'), ('FA', 'Fashion'), ('EL', 'Electronics'), ('HO', 'Home'), ('OT', 'Others')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(null=True, to='auctions.Listing'),
        ),
    ]
